### ISSUE TITLE
GPSD seems to be broken now

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#235]
Does GPSD work for you? I'm trying to deploy the gateway:

    docker run --net=host -it rhiot/deploy-gateway deploy-gateway -Pgps=true -Pcamellabs_iot_gateway_log_root_level=debug --artifact=io.rhiot:rhiot-gateway-app:0.1.2-SNAPSHOT

What I can see in logs is that GPSD component is started, GPSD endpoint is started, GPSD daemon is successfully restarted and then... CamelContext shuts down.

Can you take a look at this and tell me if the gateway works for you?? I'm not sure I broke something or what :) .

**Comment by levackt** [comment]
That exact docker command can't work for me yet, due to "No supported devices detected", I was waiting for the fix for this to be released before deploying with docker again but just pulled the latest rhiot/deploy-gateway image and it still doesn't work.
For now I deploy with the IDE by running the groovy Deployer and it works great again, before pulling it failed due to the exception below.


Exchange
---------------------------------------------------------------------------------------------------------------------------------------
Exchange[
	Id                  ID-rhiot-pi-37592-1444913394804-1-168
	ExchangePattern     OutOnly
	Headers             {breadcrumbId=ID-rhiot-pi-37592-1444913394804-1-167, CamelRedelivered=false, CamelRedeliveryCounter=0, io.rhiot.gpsd.tpvObject=TPVObject{tag=RMC, device=/dev/ttyUSB0, timestamp=1.44491355E9, timestampError=0.005, latitude=-34.070416667, longitude=18.851831667, altitude=82.3, latitudeError=10.761, longitudeError=10.571, altitudeError=35.217, course=153.98, speed=0.0, climbRate=0.0, courseError=NaN, speedError=21.52, climbRateError=NaN, mode=ThreeDimensional}}
	BodyType            io.rhiot.component.gpsd.ClientGpsCoordinates
	Body                io.rhiot.component.gpsd.ClientGpsCoordinates@8f5c1e
]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class io.rhiot.component.gpsd.ClientGpsCoordinates and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:59) ~[camel-labs-iot-gateway-0.1.1-SNAPSHOT.jar:na]
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:26) ~[camel-labs-iot-gateway-0.1.1-SNAPSHOT.jar:na]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128) ~[camel-labs-iot-gateway-0.1.1-SNAPSHOT.jar:na]
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800) ~[camel-labs-iot-gateway-0.1.1-SNAPSHOT.jar:na]
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:642) ~[camel-labs-iot-gateway-0.1.1-SNAPSHOT.jar:na]
	at org.apache.camel.component.jackson.JacksonDataFormat.marshal(JacksonDataFormat.java:148) ~[camel-labs-iot-gateway-0.1.1-SNAPSHOT.jar:na]
	at org.apache.camel.processor.MarshalProcessor.process(MarshalProcessor.java:81) ~[camel-labs-iot-gateway-0.1.1-SNAPSHOT.jar:na]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) ~[camel-labs-iot-gateway-0.1.1-SNAPSHOT.jar:na]

**Comment by hekonsek** [comment]
Have you used the `--net=host` option when running deployer from Docker?

**Comment by levackt** [comment]
Yep, and the Pi is running for sure, I can ssh into it with the default
user as well as deploy from the IDE.

Not sure if the behaviour of net=host is different on osx, anyway here's
the copy/paste and output as is

docker run --net=host -it rhiot/deploy-gateway deploy-gateway -Pgps=true
-Pcamellabs_iot_gateway_log_root_level=debug
--artifact=io.rhiot:rhiot-gateway-app:0.1.2-SNAPSHOT
Detecting devices...
No supported devices detected.

**Comment by hekonsek** [comment]
Let's come back to the dockerized deployer later.

I have narrowed the issued with GPSD. It fails only if I use `gps_enrich=kura-wifi:*.*` but works for other endpoints. I will take this one then :) .

**Comment by hekonsek** [comment]
I nailed it. My logger configuration swallowed the REST route configuration exception. That causes the CamelContext to be stopped. Everything works like a charm now.
