### ISSUE TITLE
WebCam component should not fail when non-root user is running it

### ISSUE THREAD

**Issue by hekonsek** [rhiot/rhiot#262]
When running the `mvn install` on my box, a build fails with the following exception:   

    Caused by: io.rhiot.utils.install.exception.PermissionDeniedException: You must have sufficient privileges to install package/s [v4l-utils]
	at io.rhiot.utils.install.DefaultInstaller.install(DefaultInstaller.java:152)
	at io.rhiot.component.webcam.WebcamComponent.doStart(WebcamComponent.java:87)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:3219)
	at org.apache.camel.impl.DefaultCamelContext.getComponent(DefaultCamelContext.java:404)
	... 58 more

We should only log "You must have sufficient privileges to install package/s [v4l-utils]" WARN message by default, until component option like `ignoreInstallerProblems` has been set to `false`.

/CC @levackt

**Comment by hekonsek** [comment]
Also not all Linux/webcam combination requires `v4l-utils` to be installed. For example Ubuntu + my Lenovo webcam doesn't. I will update the documentation to reflect that.

**Comment by hekonsek** [comment]
OK. Done :) . BTW Awesome work with this installer stuff!

**Comment by levackt** [comment]
Great, good looking out as usual :)
