### ISSUE TITLE
kura-quickstart works only with camel 2.16.0 only, not w/ 2.16.1

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#335]

**Comment by hekonsek** [comment]
Any idea why it happens? Have you found something in logs?

**Comment by PatrickSteiner** [comment]
Where is the Camel version defined? Can't find it in the pom.xml and via grep? Would like to manually "downgrade" to be able to proceed.

Would it maybe make sense to officially revert to an older version, so that others don't run into this issue? Not being able to run a quickstart might be annoying.

**Comment by hekonsek** [comment]
Hi,

I will try to downgrade Camel in quickstart and give it try. Then I will
try to figure out what is root cause of the issue.

BTW We plan to introduce automated tests on hosted Raspberry Pi devices via
Jenkins jobs to detect such issues sooner.

Cheers!

śr., 16.12.2015 o 08:41 użytkownik Patrick Steiner <notifications@github.com>
napisał:

> Where is the Camel version defined? Can't find it in the pom.xml and via
> grep? Would like to manually "downgrade" to be able to proceed.
>
> Would it maybe make sense to officially revert to an older version, so
> that others don't run into this issue? Not being able to run a quickstart
> might be annoying.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiot/rhiot/issues/335#issuecomment-165023936>.
>
-- 
Henryk Konsek
http://about.me/hekonsek

**Comment by hekonsek** [comment]
@gautric I've just to run the example with Camel 2.16.0 and still I can't see SCR service started.

**Comment by hekonsek** [comment]
I think I have found the motherfucker!

    DEBUG 6 The 'io.rhiot.quickstarts.kura.camel.GatewayRouter' component's configuration could not be satisfied because it is required to be initialized by a ConfigurationAdmin service Configuration object, but one was not found.

**Comment by hekonsek** [comment]
Yeah, when I change `configuration-policy="optional"` everything seems to work regardless of the Camel version. But why did it stop to work? We need to investigate it little more.

**Comment by hekonsek** [comment]
@PatrickSteiner The quickstart is working again. Can you give it a try now? If you manage see timer messages in logs, then we can schedule a call and I will show you how to edit XML routes at runtime.

**Comment by gautric** [comment]
I ve retry it, with emulator mode, you right `configuration-policy` could be root cause

**Comment by PatrickSteiner** [comment]
@hekonsek this is what I'm getting on a fresh installed / rebooted RPi

2015-12-16 10:43:02,002 [Component Resolve Thread (Bundle 6)] WARN  i.r.q.k.c.GatewayRouter - Problem when starting Kura module io.rhiot.quickstarts.kura.camel.GatewayRouter:
java.lang.IllegalArgumentException: Did not find component given by the name: properties
        at org.apache.camel.impl.DefaultCamelContext.getComponent(DefaultCamelContext.java:431)
        at io.rhiot.component.kura.router.RhiotKuraRouter.beforeStart(RhiotKuraRouter.java:106)
        at io.rhiot.quickstarts.kura.camel.GatewayRouter.beforeStart(GatewayRouter.java:23)
        at org.apache.camel.component.kura.KuraRouter.start(KuraRouter.java:49)
        at io.rhiot.component.kura.router.RhiotKuraRouter.start(RhiotKuraRouter.java:79)
        at io.rhiot.component.kura.router.RhiotKuraRouter.activate(RhiotKuraRouter.java:96)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:347)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
        at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
        at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
        at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
        at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
        at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)

**Comment by hekonsek** [comment]
Yay! Working with bleeding edge code :) .

Use `-U` option when building quickstart. Then scp updated camel-kura-0.1.3 to RPi. You are using cached version now.

**Comment by hekonsek** [comment]
By scp I mean this step:

    scp ~/.m2/repository/io/rhiot/camel-kura/0.1.3-SNAPSHOT/camel-kura-0.1.3-SNAPSHOT.jar pi@${RBPI_IP}:/tmp

**Comment by PatrickSteiner** [comment]
@hekonsek this seemed to solve the problem. Log now shows

2015-12-16 10:53:26,722 [Camel (camel-1) thread #0 - timer://heartbeat] INFO  heartbeat - Exchange[ExchangePattern: InOnly, BodyType: null, Body: [Body is null]]
2015-12-16 10:53:27,723 [Camel (camel-1) thread #0 - timer://heartbeat] INFO  heartbeat - Exchange[ExchangePattern: InOnly, BodyType: null, Body: [Body is null]]

**Comment by gautric** [comment]
+1

**Comment by gautric** [comment]
sorry for mistake @PatrickSteiner, hope you enjoy it

**Comment by hekonsek** [comment]
It's alive! It's alive!

**Comment by PatrickSteiner** [comment]
shouldn't I be seeing something in the kura Services?
![kura](https://cloud.githubusercontent.com/assets/4146860/11838145/5c03d3c0-a3e5-11e5-83b5-1c8642904f91.png)

**Comment by hekonsek** [comment]
Apparently switching `configuration-policy="optional"` disables our service from web UI, regardless of the fact that it has been properly registered. I will create a bug report for it and resolve it soon.

For now quickstart works, but you can't manage it via web UI.

**Comment by hekonsek** [comment]
New ticket for web UI issue - #338.
