### ISSUE TITLE
rhiot cmd raspbian doesn't on mac 

### ISSUE THREAD

**Issue by gautric** [rhiot/rhiot#361]
got 
`[mbp:~]$> rhiot raspbian-install disk3
No such command. Execute 'rhiot --help' to see all the available commands.`

**Comment by hekonsek** [comment]
I will check this out.

**Comment by hekonsek** [comment]
Can you try to execute the command with `docker logs -f rhiot-shell` running? You can send me out shell log output.

**Comment by gautric** [comment]
`[mbp:~]$> docker logs -f rhiot-shell
  _____  _     _       _
 |  __ \| |   (_)     | |
 | |__) | |__  _  ___ | |_
 |  _  /| '_ \| |/ _ \| __|
 | | \ \| | | | | (_) | |_
 |_|  \_\_| |_|_|\___/ \__|


2015-12-17 14:31:38.181  INFO 8 --- [           main] io.rhiot.tooling.shell.Shell             : Starting Shell on default with PID 8 (/jars/rhiot-tooling-shell-0.1.3-SNAPSHOT.jar started by root in /)
2015-12-17 14:31:38.188  INFO 8 --- [           main] io.rhiot.tooling.shell.Shell             : No profiles are active
2015-12-17 14:31:38.317  INFO 8 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@505c723c: startup date [Thu Dec 17 14:31:38 UTC 2015]; root of context hierarchy
2015-12-17 14:32:16.557  INFO 8 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2015-12-17 14:32:16.572  INFO 8 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2015-12-17 14:32:16.712  INFO 8 --- [           main] io.rhiot.tooling.shell.Shell             : Started Shell in 41.799 seconds (JVM running for 40.451)
2015-12-17 14:34:43.998  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Server session created from /127.0.0.1:35196
2015-12-17 14:34:44.331  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: server->client aes128-ctr hmac-md5 none
2015-12-17 14:34:44.332  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: client->server aes128-ctr hmac-md5 none
2015-12-17 14:34:44.621  INFO 8 --- [pool-6-thread-1] o.a.s.s.session.ServerUserAuthService    : Session rhiot@/127.0.0.1:35196 authenticated
2015-12-17 14:34:44.669  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.channel.ChannelSession   : Executing command: device-scan
2015-12-17 14:37:58.916  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Server session created from /127.0.0.1:35203
2015-12-17 14:37:59.103  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: server->client aes128-ctr hmac-md5 none
2015-12-17 14:37:59.104  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: client->server aes128-ctr hmac-md5 none
2015-12-17 14:37:59.161  INFO 8 --- [pool-6-thread-2] o.a.s.s.session.ServerUserAuthService    : Session rhiot@/127.0.0.1:35203 authenticated
2015-12-17 14:37:59.189  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.channel.ChannelSession   : Executing command: device-scan -q
2015-12-17 14:38:42.412  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Server session created from /127.0.0.1:35210
2015-12-17 14:38:42.586  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Kex: server->client aes128-ctr hmac-md5 none
2015-12-17 14:38:42.586  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Kex: client->server aes128-ctr hmac-md5 none
2015-12-17 14:38:42.662  INFO 8 --- [pool-6-thread-1] o.a.s.s.session.ServerUserAuthService    : Session rhiot@/127.0.0.1:35210 authenticated
2015-12-17 14:38:42.698  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.channel.ChannelSession   : Executing command: device-scan -q
2015-12-17 14:51:11.415  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Server session created from /127.0.0.1:35217
2015-12-17 14:51:11.631  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: server->client aes128-ctr hmac-md5 none
2015-12-17 14:51:11.631  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: client->server aes128-ctr hmac-md5 none
2015-12-17 14:51:11.675  INFO 8 --- [pool-6-thread-2] o.a.s.s.session.ServerUserAuthService    : Session rhiot@/127.0.0.1:35217 authenticated
2015-12-17 14:51:11.706  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.channel.ChannelSession   : Executing command: device-scan
2015-12-17 15:24:06.887  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Server session created from /127.0.0.1:35224
2015-12-17 15:24:07.111  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Kex: server->client aes128-ctr hmac-md5 none
2015-12-17 15:24:07.112  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Kex: client->server aes128-ctr hmac-md5 none
2015-12-17 15:24:07.166  INFO 8 --- [pool-6-thread-2] o.a.s.s.session.ServerUserAuthService    : Session rhiot@/127.0.0.1:35224 authenticated
2015-12-17 15:24:07.193  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.channel.ChannelSession   : Executing command: device-scan
2015-12-18 13:50:43.232  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Server session created from /127.0.0.1:35361
2015-12-18 13:50:43.395  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Kex: server->client aes128-ctr hmac-md5 none
2015-12-18 13:50:43.395  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Kex: client->server aes128-ctr hmac-md5 none
2015-12-18 13:50:43.443  INFO 8 --- [pool-6-thread-1] o.a.s.s.session.ServerUserAuthService    : Session rhiot@/127.0.0.1:35361 authenticated
2015-12-18 13:50:43.464  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.channel.ChannelSession   : Executing command: device-scan
2015-12-18 13:50:47.961  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Server session created from /127.0.0.1:35368
2015-12-18 13:50:48.156  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Kex: server->client aes128-ctr hmac-md5 none
2015-12-18 13:50:48.156  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Kex: client->server aes128-ctr hmac-md5 none
2015-12-18 13:50:48.200  INFO 8 --- [pool-6-thread-1] o.a.s.s.session.ServerUserAuthService    : Session rhiot@/127.0.0.1:35368 authenticated
2015-12-18 13:50:48.228  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.channel.ChannelSession   : Executing command: device-scan
2015-12-18 18:21:57.748  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Server session created from /127.0.0.1:35375
2015-12-18 18:21:57.972  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: server->client aes128-ctr hmac-md5 none
2015-12-18 18:21:57.972  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: client->server aes128-ctr hmac-md5 none
2015-12-18 18:21:58.026  INFO 8 --- [pool-6-thread-1] o.a.s.s.session.ServerUserAuthService    : Session rhiot@/127.0.0.1:35375 authenticated
2015-12-18 18:21:58.069  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.channel.ChannelSession   : Executing command: raspbian-install disk3
2015-12-18 18:22:18.301 ERROR 8 --- [          CRaSH] o.crsh.ssh.term.inline.SSHInlineCommand  : Error during command execution : raspbian-install disk3: exception: director.downloads.raspberrypi.org

java.net.UnknownHostException: director.downloads.raspberrypi.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_66-internal]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_66-internal]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_66-internal]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_66-internal]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_66-internal]
	at java.net.URL.openStream(URL.java:1038) ~[na:1.8.0_66-internal]
	at java_net_URL$openStream.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.5.jar!/:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.5.jar!/:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) ~[groovy-2.4.5.jar!/:2.4.5]
	at io.rhiot.tooling.shell.commands.RaspbianInstallCommand.execute(RaspbianInstallCommand.groovy:50) ~[rhiot-tooling-shell-0.1.3-SNAPSHOT.jar!/:na]
	at io.rhiot.tooling.shell.commands.RaspbianInstallCommand$execute.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.5.jar!/:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.5.jar!/:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-2.4.5.jar!/:2.4.5]
	at commands.raspbian_install.main(raspbian-install:33) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66-internal]
	at org.crsh.cli.impl.lang.MethodDescriptor$1.invoke(MethodDescriptor.java:164) ~[crash.cli-1.3.2.jar!/:na]
	at org.crsh.cli.impl.lang.MethodDescriptor$1.invoke(MethodDescriptor.java:106) ~[crash.cli-1.3.2.jar!/:na]
	at org.crsh.lang.impl.java.ProducerCommandMatch$1.close(ProducerCommandMatch.java:117) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.pipeline.CommandInvokerAdapter.close(CommandInvokerAdapter.java:296) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.pipeline.PipeLine.close(PipeLine.java:106) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.spi.CommandInvoker.invoke(CommandInvoker.java:52) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.CRaSHCommandProcess.doInvoke(CRaSHCommandProcess.java:39) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.CRaSHProcess.execute(CRaSHProcess.java:60) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.async.AsyncProcess$2.call(AsyncProcess.java:207) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.async.AsyncProcess$2.call(AsyncProcess.java:177) ~[crash.shell-1.3.2.jar!/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66-internal]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]

2015-12-18 18:22:18.306 ERROR 8 --- [pool-3-thread-8] o.crsh.shell.impl.command.CRaSHSession   : Error while evaluating request 'raspbian-install disk3' raspbian-install disk3: exception: director.downloads.raspberrypi.org

java.net.UnknownHostException: director.downloads.raspberrypi.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_66-internal]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_66-internal]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_66-internal]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_66-internal]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_66-internal]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512) ~[na:1.8.0_66-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_66-internal]
	at java.net.URL.openStream(URL.java:1038) ~[na:1.8.0_66-internal]
	at java_net_URL$openStream.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.5.jar!/:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.5.jar!/:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) ~[groovy-2.4.5.jar!/:2.4.5]
	at io.rhiot.tooling.shell.commands.RaspbianInstallCommand.execute(RaspbianInstallCommand.groovy:50) ~[rhiot-tooling-shell-0.1.3-SNAPSHOT.jar!/:na]
	at io.rhiot.tooling.shell.commands.RaspbianInstallCommand$execute.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.5.jar!/:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.5.jar!/:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-2.4.5.jar!/:2.4.5]
	at commands.raspbian_install.main(raspbian-install:33) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66-internal]
	at org.crsh.cli.impl.lang.MethodDescriptor$1.invoke(MethodDescriptor.java:164) ~[crash.cli-1.3.2.jar!/:na]
	at org.crsh.cli.impl.lang.MethodDescriptor$1.invoke(MethodDescriptor.java:106) ~[crash.cli-1.3.2.jar!/:na]
	at org.crsh.lang.impl.java.ProducerCommandMatch$1.close(ProducerCommandMatch.java:117) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.pipeline.CommandInvokerAdapter.close(CommandInvokerAdapter.java:296) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.pipeline.PipeLine.close(PipeLine.java:106) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.spi.CommandInvoker.invoke(CommandInvoker.java:52) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.CRaSHCommandProcess.doInvoke(CRaSHCommandProcess.java:39) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.command.CRaSHProcess.execute(CRaSHProcess.java:60) ~[crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.async.AsyncProcess$2.call(AsyncProcess.java:207) [crash.shell-1.3.2.jar!/:na]
	at org.crsh.shell.impl.async.AsyncProcess$2.call(AsyncProcess.java:177) [crash.shell-1.3.2.jar!/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66-internal]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]

2015-12-18 18:32:36.254  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Server session created from /127.0.0.1:35376
2015-12-18 18:32:36.531  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: server->client aes128-ctr hmac-md5 none
2015-12-18 18:32:36.531  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: client->server aes128-ctr hmac-md5 none
2015-12-18 18:32:36.591  INFO 8 --- [pool-6-thread-2] o.a.s.s.session.ServerUserAuthService    : Session rhiot@/127.0.0.1:35376 authenticated
2015-12-18 18:32:36.660  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.channel.ChannelSession   : Executing command: device-scan
2015-12-18 18:33:13.733  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Server session created from /127.0.0.1:35383
2015-12-18 18:33:14.070  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: server->client aes128-ctr hmac-md5 none
2015-12-18 18:33:14.071  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Kex: client->server aes128-ctr hmac-md5 none
2015-12-18 18:33:14.136  INFO 8 --- [pool-6-thread-2] o.a.s.s.session.ServerUserAuthService    : Session rhiot@/127.0.0.1:35383 authenticated
2015-12-18 18:33:14.230  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.channel.ChannelSession   : Executing command: device-scan
2015-12-18 19:44:35.169  INFO 8 --- [pool-6-thread-2] o.a.sshd.server.session.ServerSession    : Server session created from /127.0.0.1:35390
2015-12-18 19:44:35.471  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Kex: server->client aes128-ctr hmac-md5 none
2015-12-18 19:44:35.471  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.session.ServerSession    : Kex: client->server aes128-ctr hmac-md5 none
2015-12-18 19:44:35.535  INFO 8 --- [pool-6-thread-1] o.a.s.s.session.ServerUserAuthService    : Session rhiot@/127.0.0.1:35390 authenticated
2015-12-18 19:44:35.577  INFO 8 --- [pool-6-thread-1] o.a.sshd.server.channel.ChannelSession   : Executing command: device-scan
`
