### ISSUE TITLE
i.r.c.c.o.OpenalprProducerIntegrationTest failure

### ISSUE THREAD

**Issue by starksm64** [rhiot/rhiot#585]
I'm seeing the i.r.c.c.o.OpenalprProducerIntegrationTest test fail on two different platforms when trying to build the current rhiot git repo. When I run the test in my ide, the following output is produced.

/usr/lib/jvm/jdk1.8.0_92/bin/java -ea -Didea.launcher.port=7532 -Didea.launcher.bin.path=/home/sstark/Downloads/idea-IC-145.597.3/bin -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath /home/sstark/Downloads/idea-IC-145.597.3/lib/idea_rt.jar:/home/sstark/Downloads/idea-IC-145.597.3/plugins/junit/lib/junit-rt.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/deploy.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/ext/dnsns.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/ext/jaccess.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/ext/localedata.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/ext/nashorn.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/ext/sunec.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/ext/zipfs.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/javaws.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/jce.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/jfxswt.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/management-agent.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/plugin.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/resources.jar:/usr/lib/jvm/jdk1.8.0_92/jre/lib/rt.jar:/home/sstark/rhiot/camel/openalpr/target/test-classes:/home/sstark/rhiot/camel/openalpr/target/classes:/home/sstark/rhiot/lib/utils/target/classes:/home/sstark/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar:/home/sstark/.m2/repository/joda-time/joda-time/2.8.2/joda-time-2.8.2.jar:/home/sstark/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/sstark/.m2/repository/org/codehaus/groovy/groovy/2.4.4/groovy-2.4.4.jar:/home/sstark/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar:/home/sstark/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar:/home/sstark/.m2/repository/org/apache/camel/camel-netty4-http/2.17.0/camel-netty4-http-2.17.0.jar:/home/sstark/.m2/repository/org/apache/camel/camel-netty4/2.17.0/camel-netty4-2.17.0.jar:/home/sstark/.m2/repository/io/netty/netty-all/4.0.34.Final/netty-all-4.0.34.Final.jar:/home/sstark/.m2/repository/commons-pool/commons-pool/1.6/commons-pool-1.6.jar:/home/sstark/.m2/repository/com/sun/xml/bind/jaxb-core/2.2.11/jaxb-core-2.2.11.jar:/home/sstark/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.11/jaxb-impl-2.2.11.jar:/home/sstark/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/home/sstark/.m2/repository/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar:/home/sstark/.m2/repository/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.jar:/home/sstark/.m2/repository/com/google/truth/truth/0.28/truth-0.28.jar:/home/sstark/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/sstark/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/sstark/rhiot/cloudplatform/encoding/json/target/classes:/home/sstark/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.6.5/jackson-databind-2.6.5.jar:/home/sstark/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.6.5/jackson-annotations-2.6.5.jar:/home/sstark/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.6.5/jackson-core-2.6.5.jar:/home/sstark/rhiot/cloudplatform/encoding/spi/target/classes:/home/sstark/rhiot/cloudplatform/service/binding/target/classes:/home/sstark/.m2/repository/org/apache/camel/camel-amqp/2.16.2/camel-amqp-2.16.2.jar:/home/sstark/.m2/repository/org/apache/qpid/qpid-amqp-1-0-client-jms/0.28/qpid-amqp-1-0-client-jms-0.28.jar:/home/sstark/.m2/repository/org/apache/qpid/qpid-amqp-1-0-common/0.28/qpid-amqp-1-0-common-0.28.jar:/home/sstark/.m2/repository/org/apache/qpid/qpid-amqp-1-0-client/0.28/qpid-amqp-1-0-client-0.28.jar:/home/sstark/.m2/repository/org/apache/qpid/qpid-client/0.28/qpid-client-0.28.jar:/home/sstark/.m2/repository/org/apache/qpid/qpid-common/0.28/qpid-common-0.28.jar:/home/sstark/.m2/repository/org/apache/geronimo/specs/geronimo-jms_1.1_spec/1.1.1/geronimo-jms_1.1_spec-1.1.1.jar:/home/sstark/.m2/repository/org/apache/camel/camel-test/2.17.0/camel-test-2.17.0.jar:/home/sstark/.m2/repository/org/apache/camel/camel-core/2.17.0/camel-core-2.17.0.jar:/home/sstark/rhiot/cloudplatform/runtime/spring/target/classes:/home/sstark/.m2/repository/org/apache/camel/camel-jms/2.17.0/camel-jms-2.17.0.jar:/home/sstark/.m2/repository/org/apache/camel/camel-spring/2.17.0/camel-spring-2.17.0.jar:/home/sstark/.m2/repository/org/springframework/spring-jms/4.2.4.RELEASE/spring-jms-4.2.4.RELEASE.jar:/home/sstark/.m2/repository/org/springframework/spring-messaging/4.2.4.RELEASE/spring-messaging-4.2.4.RELEASE.jar:/home/sstark/.m2/repository/org/springframework/spring-tx/4.2.4.RELEASE/spring-tx-4.2.4.RELEASE.jar:/home/sstark/.m2/repository/org/springframework/boot/spring-boot-starter/1.3.2.RELEASE/spring-boot-starter-1.3.2.RELEASE.jar:/home/sstark/.m2/repository/org/springframework/boot/spring-boot/1.3.2.RELEASE/spring-boot-1.3.2.RELEASE.jar:/home/sstark/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.3.2.RELEASE/spring-boot-autoconfigure-1.3.2.RELEASE.jar:/home/sstark/.m2/repository/org/springframework/boot/spring-boot-starter-logging/1.3.2.RELEASE/spring-boot-starter-logging-1.3.2.RELEASE.jar:/home/sstark/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.13/jcl-over-slf4j-1.7.13.jar:/home/sstark/.m2/repository/org/slf4j/jul-to-slf4j/1.7.13/jul-to-slf4j-1.7.13.jar:/home/sstark/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.13/log4j-over-slf4j-1.7.13.jar:/home/sstark/.m2/repository/org/yaml/snakeyaml/1.16/snakeyaml-1.16.jar:/home/sstark/.m2/repository/org/apache/camel/camel-spring-boot/2.17.0/camel-spring-boot-2.17.0.jar:/home/sstark/rhiot/cloudplatform/connector/target/classes:/home/sstark/rhiot/spring/activemq/target/classes:/home/sstark/.m2/repository/org/apache/activemq/activemq-broker/5.13.1/activemq-broker-5.13.1.jar:/home/sstark/.m2/repository/org/apache/activemq/activemq-client/5.13.1/activemq-client-5.13.1.jar:/home/sstark/.m2/repository/org/apache/activemq/activemq-openwire-legacy/5.12.2/activemq-openwire-legacy-5.12.2.jar:/home/sstark/.m2/repository/org/apache/activemq/activemq-amqp/5.13.1/activemq-amqp-5.13.1.jar:/home/sstark/.m2/repository/org/apache/qpid/proton-j/0.11.1/proton-j-0.11.1.jar:/home/sstark/.m2/repository/org/fusesource/hawtbuf/hawtbuf/1.11/hawtbuf-1.11.jar:/home/sstark/.m2/repository/org/apache/activemq/activemq-mqtt/5.13.1/activemq-mqtt-5.13.1.jar:/home/sstark/.m2/repository/org/apache/activemq/protobuf/activemq-protobuf/1.1/activemq-protobuf-1.1.jar:/home/sstark/.m2/repository/org/fusesource/mqtt-client/mqtt-client/1.12/mqtt-client-1.12.jar:/home/sstark/.m2/repository/org/fusesource/hawtdispatch/hawtdispatch-transport/1.22/hawtdispatch-transport-1.22.jar:/home/sstark/.m2/repository/org/fusesource/hawtdispatch/hawtdispatch/1.22/hawtdispatch-1.22.jar:/home/sstark/.m2/repository/org/apache/geronimo/specs/geronimo-j2ee-management_1.1_spec/1.0.1/geronimo-j2ee-management_1.1_spec-1.0.1.jar:/home/sstark/.m2/repository/commons-net/commons-net/3.3/commons-net-3.3.jar:/home/sstark/.m2/repository/org/apache/activemq/activemq-http/5.12.2/activemq-http-5.12.2.jar:/home/sstark/.m2/repository/org/apache/activemq/activemq-spring/5.12.2/activemq-spring-5.12.2.jar:/home/sstark/.m2/repository/org/apache/xbean/xbean-spring/3.18/xbean-spring-3.18.jar:/home/sstark/.m2/repository/org/apache/activemq/activemq-pool/5.13.1/activemq-pool-5.13.1.jar:/home/sstark/.m2/repository/org/apache/activemq/activemq-jms-pool/5.13.1/activemq-jms-pool-5.13.1.jar:/home/sstark/.m2/repository/org/apache/geronimo/specs/geronimo-jta_1.0.1B_spec/1.0.1/geronimo-jta_1.0.1B_spec-1.0.1.jar:/home/sstark/.m2/repository/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar:/home/sstark/.m2/repository/org/apache/activemq/activemq-stomp/5.12.2/activemq-stomp-5.12.2.jar:/home/sstark/.m2/repository/org/eclipse/jetty/aggregate/jetty-all/8.1.16.v20140903/jetty-all-8.1.16.v20140903.jar:/home/sstark/.m2/repository/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.jar:/home/sstark/.m2/repository/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar:/home/sstark/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar:/home/sstark/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/sstark/.m2/repository/com/thoughtworks/xstream/xstream/1.4.8/xstream-1.4.8.jar:/home/sstark/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar:/home/sstark/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar:/home/sstark/.m2/repository/org/apache/activemq/activemq-kahadb-store/5.12.2/activemq-kahadb-store-5.12.2.jar:/home/sstark/.m2/repository/org/springframework/spring-web/4.2.4.RELEASE/spring-web-4.2.4.RELEASE.jar:/home/sstark/.m2/repository/org/springframework/spring-aop/4.2.4.RELEASE/spring-aop-4.2.4.RELEASE.jar:/home/sstark/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/sstark/.m2/repository/org/springframework/spring-beans/4.2.4.RELEASE/spring-beans-4.2.4.RELEASE.jar:/home/sstark/.m2/repository/org/springframework/spring-context/4.2.4.RELEASE/spring-context-4.2.4.RELEASE.jar:/home/sstark/.m2/repository/org/springframework/spring-expression/4.2.4.RELEASE/spring-expression-4.2.4.RELEASE.jar:/home/sstark/.m2/repository/org/springframework/spring-core/4.2.4.RELEASE/spring-core-4.2.4.RELEASE.jar:/home/sstark/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 io.rhiot.cloudplatform.camel.openalpr.OpenalprProducerIntegrationTest
21:35:57.020 [main] INFO  i.r.c.c.o.OpenalprProducerIntegrationTest - ********************************************************************************
21:35:57.022 [main] INFO  i.r.c.c.o.OpenalprProducerIntegrationTest - Testing: shouldFindPlate(io.rhiot.cloudplatform.camel.openalpr.OpenalprProducerIntegrationTest)
21:35:57.022 [main] INFO  i.r.c.c.o.OpenalprProducerIntegrationTest - ********************************************************************************
21:35:57.022 [main] DEBUG i.r.c.c.o.OpenalprProducerIntegrationTest - setUp test
21:35:57.039 [main] DEBUG i.r.c.c.o.OpenalprProducerIntegrationTest - Using jndi.properties from classpath root
21:35:57.045 [main] DEBUG org.eclipse.jetty.util.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog
21:35:57.046 [main] DEBUG jndi - InitialContextFactory.getInitialContext()
21:35:57.049 [main] DEBUG jndi - Created initial context delegate for local namespace:org.eclipse.jetty.jndi.local.localContextRoot@1e6d1014
21:35:57.190 [main] DEBUG o.a.c.impl.SharedProducerServicePool - Starting service pool: org.apache.camel.impl.SharedProducerServicePool@2641e737
21:35:57.194 [main] DEBUG o.a.camel.impl.DefaultCamelContext - Using ComponentResolver: org.apache.camel.impl.DefaultComponentResolver@376b4233 to resolve component with name: properties
21:35:57.194 [main] DEBUG jndi - Looking up name="properties"
21:35:57.194 [main] DEBUG o.a.c.impl.DefaultComponentResolver - Found component: properties in registry: null
21:35:57.197 [main] DEBUG o.a.c.impl.DefaultComponentResolver - Found component: properties via type: org.apache.camel.component.properties.PropertiesComponent via: META-INF/services/org/apache/camel/component/properties
21:35:57.207 [main] DEBUG i.r.c.c.o.OpenalprProducerIntegrationTest - Using created route builder: Routes: []
21:35:57.207 [main] DEBUG o.a.camel.impl.DefaultCamelContext - Adding routes from builder: Routes: []
21:35:57.208 [main] INFO  o.a.camel.impl.DefaultCamelContext - Apache Camel 2.17.0 (CamelContext: camel-1) is starting
21:35:57.209 [main] DEBUG o.a.camel.impl.DefaultCamelContext - Using ClassResolver=org.apache.camel.impl.DefaultClassResolver@1ee807c6, PackageScanClassResolver=org.apache.camel.impl.DefaultPackageScanClassResolver@76a4d6c, ApplicationContextClassLoader=null
21:35:57.209 [main] INFO  o.a.c.m.DefaultManagementStrategy - JMX is disabled
21:35:57.218 [main] DEBUG o.a.c.i.c.AnnotationTypeConverterLoader - Found 3 packages with 16 @Converter classes to load
21:35:57.243 [main] DEBUG o.a.c.i.c.AnnotationTypeConverterLoader - Loading file META-INF/services/org/apache/camel/TypeConverter to retrieve list of packages, from url: jar:file:/home/sstark/.m2/repository/org/apache/camel/camel-netty4-http/2.17.0/camel-netty4-http-2.17.0.jar!/META-INF/services/org/apache/camel/TypeConverter
21:35:57.243 [main] DEBUG o.a.c.i.c.AnnotationTypeConverterLoader - Loading file META-INF/services/org/apache/camel/TypeConverter to retrieve list of packages, from url: jar:file:/home/sstark/.m2/repository/org/apache/camel/camel-netty4/2.17.0/camel-netty4-2.17.0.jar!/META-INF/services/org/apache/camel/TypeConverter
21:35:57.243 [main] DEBUG o.a.c.i.c.AnnotationTypeConverterLoader - Loading file META-INF/services/org/apache/camel/TypeConverter to retrieve list of packages, from url: jar:file:/home/sstark/.m2/repository/org/apache/camel/camel-core/2.17.0/camel-core-2.17.0.jar!/META-INF/services/org/apache/camel/TypeConverter
21:35:57.244 [main] DEBUG o.a.c.i.c.AnnotationTypeConverterLoader - Loading file META-INF/services/org/apache/camel/TypeConverter to retrieve list of packages, from url: jar:file:/home/sstark/.m2/repository/org/apache/camel/camel-spring/2.17.0/camel-spring-2.17.0.jar!/META-INF/services/org/apache/camel/TypeConverter
21:35:57.246 [main] DEBUG o.a.c.i.c.AnnotationTypeConverterLoader - Loaded 3 @Converter classes
21:35:57.251 [main] INFO  o.a.c.i.c.DefaultTypeConverter - Loaded 197 type converters
21:35:57.251 [main] DEBUG o.a.c.i.SharedPollingConsumerServicePool - Starting service pool: org.apache.camel.impl.SharedPollingConsumerServicePool@3a079870
21:35:57.252 [main] INFO  o.a.camel.impl.DefaultCamelContext - AllowUseOriginalMessage is enabled. If access to the original message is not needed, then its recommended to turn this option off as it may improve performance.
21:35:57.252 [main] INFO  o.a.camel.impl.DefaultCamelContext - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
21:35:57.252 [main] INFO  o.a.camel.impl.DefaultCamelContext - Total 0 routes, of which 0 are started.
21:35:57.254 [main] INFO  o.a.camel.impl.DefaultCamelContext - Apache Camel 2.17.0 (CamelContext: camel-1) started in 0.044 seconds
21:35:57.254 [main] DEBUG i.r.c.c.o.OpenalprProducerIntegrationTest - Routing Rules are: []
21:35:57.257 [main] DEBUG o.a.camel.impl.DefaultCamelContext - Using ComponentResolver: org.apache.camel.impl.DefaultComponentResolver@376b4233 to resolve component with name: openalpr
21:35:57.257 [main] DEBUG jndi - Looking up name="openalpr"
21:35:57.257 [main] DEBUG o.a.c.impl.DefaultComponentResolver - Found component: openalpr in registry: null
21:35:57.258 [main] DEBUG o.a.c.impl.DefaultComponentResolver - Found component: openalpr via type: io.rhiot.cloudplatform.camel.openalpr.OpenalprComponent via: META-INF/services/org/apache/camel/component/openalpr
21:35:57.259 [main] DEBUG o.apache.camel.impl.DefaultComponent - Creating endpoint uri=[openalpr://plateReader], path=[plateReader]
21:35:57.261 [main] DEBUG o.a.camel.impl.DefaultCamelContext - openalpr://plateReader converted to endpoint: Endpoint[openalpr://plateReader] by component: io.rhiot.cloudplatform.camel.openalpr.OpenalprComponent@7a52f2a2
21:35:57.265 [main] DEBUG org.apache.camel.impl.ProducerCache - >>>> Endpoint[openalpr://plateReader] Exchange[]
21:35:57.401 [main] DEBUG i.r.c.c.openalpr.OpenalprProducer - About to process image file: /tmp/openalpr-workdir/2ba1aeee-4eb3-4bb3-b636-caab7675f104.jpg
21:35:57.402 [main] DEBUG i.r.c.c.openalpr.OpenalprProducer - About to execute command: [docker, run, -t, -v, /tmp/openalpr-workdir:/data:ro, rhiot/openalpr:0.1.4-SNAPSHOT, -c, eu, 2ba1aeee-4eb3-4bb3-b636-caab7675f104.jpg]
21:35:57.426 [main] DEBUG i.r.c.c.openalpr.OpenalprProducer - Raw output of the alpr command: [Cannot connect to the Docker daemon. Is the docker daemon running on this host?]
21:35:57.434 [main] DEBUG i.r.c.c.openalpr.OpenalprProducer - Deleting image file: /tmp/openalpr-workdir/2ba1aeee-4eb3-4bb3-b636-caab7675f104.jpg
21:35:57.436 [main] INFO  i.r.c.c.o.OpenalprProducerIntegrationTest - ********************************************************************************
21:35:57.436 [main] INFO  i.r.c.c.o.OpenalprProducerIntegrationTest - Testing done: shouldFindPlate(io.rhiot. cloudplatform.camel.openalpr.OpenalprProducerIntegrationTest)
21:35:57.436 [main] INFO  i.r.c.c.o.OpenalprProducerIntegrationTest - Took: 0.182 seconds (182 millis)
21:35:57.438 [main] INFO  i.r.c.c.o.OpenalprProducerIntegrationTest - ********************************************************************************
21:35:57.438 [main] DEBUG o.a.c.test.junit4.CamelTestSupport - tearDown test
21:35:57.438 [main] DEBUG o.a.c.i.SharedPollingConsumerServicePool - Stopping service pool: org.apache.camel.impl.SharedPollingConsumerServicePool@3a079870
21:35:57.439 [main] INFO  o.a.camel.impl.DefaultCamelContext - Apache Camel 2.17.0 (CamelContext: camel-1) is shutting down
21:35:57.439 [main] DEBUG o.a.c.i.DefaultAsyncProcessorAwaitManager - Shutting down with no inflight threads.
21:35:57.440 [main] DEBUG o.a.c.impl.DefaultInflightRepository - Shutting down with no inflight exchanges.
21:35:57.440 [main] DEBUG o.a.c.impl.SharedProducerServicePool - Stopping service pool: org.apache.camel.impl.SharedProducerServicePool@2641e737
21:35:57.440 [main] DEBUG org.apache.camel.util.EventHelper - Ignoring notifying event Stopped CamelContext: camel-1. The EventNotifier has not been started yet: org.apache.camel.impl.DefaultRuntimeEndpointRegistry@693fe6c9
21:35:57.443 [main] DEBUG o.a.camel.util.IntrospectionSupport - Clearing cache[size=0, hits=0, misses=0, evicted=0]
21:35:57.443 [main] INFO  o.a.camel.impl.DefaultCamelContext - Apache Camel 2.17.0 (CamelContext: camel-1) uptime 0.235 seconds
21:35:57.443 [main] INFO  o.a.camel.impl.DefaultCamelContext - Apache Camel 2.17.0 (CamelContext: camel-1) is shutdown in 0.004 seconds

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at io.rhiot.cloudplatform.camel.openalpr.OpenalprProducerIntegrationTest.shouldFindPlate(OpenalprProducerIntegrationTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

21:35:57.450 [main] DEBUG o.a.c.test.junit4.CamelTestSupport - tearDownAfterClass test

Process finished with exit code 255

**Comment by hekonsek** [comment]
Hi Scott,

Just to be sure - in both cases you are running Docker on virtual machine? If so, then what VM is that?

**Comment by gautric** [comment]
rhiot/rhiot#559

**Comment by gautric** [comment]
FYI, 
It is not yet official from Rhiot team, 
but `mvn clean package` process should work Docker for Mac  > 1.11.1-beta10 (build: 6662) [Beta process]

**Comment by starksm64** [comment]
No, I'm just building it using the first description of how to build from: https://rhiot.gitbooks.io/rhiotdocumentation/content/building/building.html

Building Rhiot

All you need to build the project is Maven 3 and Java 8 JDK

git clone https://github.com/rhiot/rhiot.git
cd rhiot
mvn install
